[package]
name = "handling"
version = "0.1.0"
authors = ["hageshtrem <hageshtrem@yahoo.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.3"