version: "3.8"
services:
  pathfinder:
    build: ./pathfinder
    ports:
      - "50051:50051"
    environment:
      PORT: ":50051"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  booking:
    build: ./booking
    restart: always
    depends_on:
      - pathfinder
      - rabbitmq
    ports:
      - "5051:5051"
    environment:
      PORT: ":5051"
      ROUTING_ADDR: "pathfinder:50051"
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672/%2f"
  tracking:
    build: ./tracking
    restart: always
    depends_on:
      - rabbitmq
    ports:
     - "5052:5052"
    environment:
      PORT: ":5052"
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672/%2f"
  handling:
    build: ./handling
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "5053:5053"
    environment:
      ADDR: "0.0.0.0:5053"
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672/%2f"
  apigateway:
    build: ./apigateway
    # restart: always
    depends_on:
      - booking
      - tracking
      - handling
    ports:
      - "8080:8080"
      - "9901:9901"
    environment:
      TRACKING_SVC_PORT: "5052"